all_data = {u'American Football': {u'': {'1': u'',
                              '2': u'',
                              'Date': u'',
                              'League-division': u'',
                              'Match-category': u'',
                              'Time': u'',
                              'match-code': u'',
                              'o': u'',
                              'u': u'',
                              'x': u''}},
 u'Badminton': {u'': {'1': u'',
                      '2': u'',
                      'Date': u'',
                      'League-division': u'',
                      'Match-category': u'',
                      'Time': u'',
                      'match-code': u'',
                      'o': u'',
                      'u': u'',
                      'x': u''}},
 u'Baseball': {u'': {'1': u'',
                     '2': u'',
                     'Date': u'',
                     'League-division': u'',
                     'Match-category': u'',
                     'Time': u'',
                     'match-code': u'',
                     'o': u'',
                     'u': u'',
                     'x': u''}},
 u'Basketball': {u'': {'1': u'',
                       '2': u'',
                       'Date': u'',
                       'League-division': u'',
                       'Match-category': u'',
                       'Time': u'',
                       'match-code': u'',
                       'o': u'',
                       'u': u'',
                       'x': u''}},
 u'Boxing': {u'': {'1': u'',
                   '2': u'',
                   'Date': u'',
                   'League-division': u'',
                   'Match-category': u'',
                   'Time': u'',
                   'match-code': u'',
                   'o': u'',
                   'u': u'',
                   'x': u''}},
 u'Cricket': {u'': {'1': u'',
                    '2': u'',
                    'Date': u'',
                    'League-division': u'',
                    'Match-category': u'',
                    'Time': u'',
                    'match-code': u'',
                    'o': u'',
                    'u': u'',
                    'x': u''}},
 u'Darts': {u'': {'1': u'',
                  '2': u'',
                  'Date': u'',
                  'League-division': u'',
                  'Match-category': u'',
                  'Time': u'',
                  'match-code': u'',
                  'o': u'',
                  'u': u'',
                  'x': u''}},
 u'Floorball': {u'': {'1': u'',
                      '2': u'',
                      'Date': u'',
                      'League-division': u'',
                      'Match-category': u'',
                      'Time': u'',
                      'match-code': u'',
                      'o': u'',
                      'u': u'',
                      'x': u''},
                u'Classic Tampere v TPS': {'1': u'1.35',
                                           '2': u'4.10',
                                           'Date': u'7 Oct',
                                           'League-division': u'Salibandyliiga',
                                           'Match-category': u'Finland',
                                           'Time': u'18:30',
                                           'match-code': u'5243',
                                           'o': u'1.80',
                                           'u': u'1.80',
                                           'x': u'7.00'},
                u'Endre IF v Ronnby IBK': {'1': u'1.95',
                                           '2': u'2.45',
                                           'Date': u'9 Oct',
                                           'League-division': u'Svenska Superligan, Women',
                                           'Match-category': u'Sweden',
                                           'Time': u'14:00',
                                           'match-code': u'9096',
                                           'o': u'1.95',
                                           'u': u'1.65',
                                           'x': u'5.30'},
                u'FBC Uppsala v Warberg IC': {'1': u'1.30',
                                              '2': u'5.00',
                                              'Date': u'8 Oct',
                                              'League-division': u'Svenska Superligan, Women',
                                              'Match-category': u'Sweden',
                                              'Time': u'15:00',
                                              'match-code': u'8112',
                                              'o': u'1.70',
                                              'u': u'1.85',
                                              'x': u'6.00'},
                u'Hollvikens Ibf v IK Sirius Ibk': {'1': u'1.95',
                                                    '2': u'2.35',
                                                    'Date': u'8 Oct',
                                                    'League-division': u'Svenska Superligan',
                                                    'Match-category': u'Sweden',
                                                    'Time': u'16:10',
                                                    'match-code': u'8108',
                                                    'o': u'1.95',
                                                    'u': u'1.65',
                                                    'x': u'5.50'},
                u'IBF Falun v Mullsjo Ais': {'1': u'1.20',
                                             '2': u'6.00',
                                             'Date': u'8 Oct',
                                             'League-division': u'Svenska Superligan',
                                             'Match-category': u'Sweden',
                                             'Time': u'17:00',
                                             'match-code': u'8107',
                                             'o': u'1.80',
                                             'u': u'1.80',
                                             'x': u'8.30'},
                u'Iksu v FBC Kalmarsund': {'1': u'1.01',
                                           '2': u'16',
                                           'Date': u'8 Oct',
                                           'League-division': u'Svenska Superligan, Women',
                                           'Match-category': u'Sweden',
                                           'Time': u'17:00',
                                           'match-code': u'8115',
                                           'o': u'1.70',
                                           'u': u'1.85',
                                           'x': u'16'},
                u'Thorengruppen SK v Vaxjo Ibk': {'1': u'3.70',
                                                  '2': u'1.45',
                                                  'Date': u'9 Oct',
                                                  'League-division': u'Svenska Superligan',
                                                  'Match-category': u'Sweden',
                                                  'Time': u'14:00',
                                                  'match-code': u'9081',
                                                  'o': u'1.70',
                                                  'u': u'1.90',
                                                  'x': u'6.50'}},
 u'Football': {u'': {'1': u'',
                     '2': u'',
                     'Date': u'',
                     'League-division': u'',
                     'Match-category': u'',
                     'Time': u'',
                     'match-code': u'',
                     'o': u'',
                     'u': u'',
                     'x': u''},
               u'1 FC Cologne II v Fortuna Dusseldorf II': {'1': u'1.80',
                                                            '2': u'3.70',
                                                            'Date': u'7 Oct',
                                                            'League-division': u'Regionalliga West',
                                                            'Match-category': u'Germany Amateur',
                                                            'Time': u'15:00',
                                                            'match-code': u'5141',
                                                            'o': u'1.80',
                                                            'u': u'2.00',
                                                            'x': u'3.45'},
               u'AIN Fakroun v US Biskra': {'1': u'1.80',
                                            '2': u'4.50',
                                            'Date': u'7 Oct',
                                            'League-division': u'Ligue 2',
                                            'Match-category': u'Algeria',
                                            'Time': u'18:00',
                                            'match-code': u'5179',
                                            'o': u'1.60',
                                            'u': u'2.35',
                                            'x': u'2.95'},
               u'Algeria v Cameroon': {'1': u'1.70',
                                       '2': u'4.30',
                                       'Date': u'9 Oct',
                                       'League-division': u'World Cup Qual. CAF Group B',
                                       'Match-category': u'International',
                                       'Time': u'22:30',
                                       'match-code': u'7556',
                                       'o': u'2.30',
                                       'u': u'1.60',
                                       'x': u'3.40'},
               u'Belarus v Luxembourg': {'1': u'1.25',
                                         '2': u'14.50',
                                         'Date': u'10 Oct',
                                         'League-division': u'World Cup Qual. UEFA Group A',
                                         'Match-category': u'International',
                                         'Time': u'21:45',
                                         'match-code': u'1012',
                                         'o': u'1.70',
                                         'u': u'2.10',
                                         'x': u'4.80'},
               u'Bhayangkara Surabaya United v Pusamania Borneo': {'1': u'1.55',
                                                                   '2': u'5.30',
                                                                   'Date': u'7 Oct',
                                                                   'League-division': u'Super League',
                                                                   'Match-category': u'Indonesia',
                                                                   'Time': u'12:00',
                                                                   'match-code': u'5171',
                                                                   'o': u'1.90',
                                                                   'u': u'1.90',
                                                                   'x': u'3.60'},
               u'Brisbane Roar FC v Melbourne Victory': {'1': u'2.30',
                                                         '2': u'2.75',
                                                         'Date': u'7 Oct',
                                                         'League-division': u'A-League',
                                                         'Match-category': u'Australia',
                                                         'Time': u'11:50',
                                                         'match-code': u'5541',
                                                         'o': u'1.70',
                                                         'u': u'2.10',
                                                         'x': u'3.35'},
               u'Bulgaria (U 21) v Denmark (U 21)': {'1': u'3.05',
                                                     '2': u'2.05',
                                                     'Date': u'7 Oct',
                                                     'League-division': u'U21 EURO, Qualification, Group 5',
                                                     'Match-category': u'International Youth',
                                                     'Time': u'18:00',
                                                     'match-code': u'5058',
                                                     'o': u'1.85',
                                                     'u': u'1.90',
                                                     'x': u'3.25'},
               u'Burkina Faso v South Africa': {'1': u'2.10',
                                                '2': u'2.85',
                                                'Date': u'8 Oct',
                                                'League-division': u'World Cup Qual. CAF Group D',
                                                'Match-category': u'International',
                                                'Time': u'21:00',
                                                'match-code': u'6056',
                                                'o': u'2.05',
                                                'u': u'1.75',
                                                'x': u'3.35'},
               u'Congo v Egypt': {'1': u'2.50',
                                  '2': u'2.55',
                                  'Date': u'9 Oct',
                                  'League-division': u'World Cup Qual. CAF Group E',
                                  'Match-category': u'International',
                                  'Time': u'17:30',
                                  'match-code': u'7026',
                                  'o': u'2.40',
                                  'u': u'1.55',
                                  'x': u'3.05'},
               u'DR Congo v Libya': {'1': u'1.55',
                                     '2': u'4.90',
                                     'Date': u'8 Oct',
                                     'League-division': u'World Cup Qual. CAF Group A',
                                     'Match-category': u'International',
                                     'Time': u'20:30',
                                     'match-code': u'6133',
                                     'o': u'2.15',
                                     'u': u'1.70',
                                     'x': u'3.60'},
               u'Faroe Islands (U 21) v Austria (U 21)': {'1': u'13.50',
                                                          '2': u'1.08',
                                                          'Date': u'7 Oct',
                                                          'League-division': u'U21 EURO, Qualification, Group 7',
                                                          'Match-category': u'International Youth',
                                                          'Time': u'17:30',
                                                          'match-code': u'5085',
                                                          'o': u'2.15',
                                                          'u': u'1.65',
                                                          'x': u'8.50'},
               u'Finland (U 21) v Azerbaijan (U 21)': {'1': u'1.50',
                                                       '2': u'5.00',
                                                       'Date': u'7 Oct',
                                                       'League-division': u'U21 EURO, Qualification, Group 7',
                                                       'Match-category': u'International Youth',
                                                       'Time': u'18:30',
                                                       'match-code': u'5083',
                                                       'o': u'1.70',
                                                       'u': u'2.10',
                                                       'x': u'3.90'},
               u'France v Bulgaria': {'1': u'1.12',
                                      '2': u'19.50',
                                      'Date': u'7 Oct',
                                      'League-division': u'World Cup Qual. UEFA Group A',
                                      'Match-category': u'International',
                                      'Time': u'21:45',
                                      'match-code': u'5548',
                                      'o': u'2.20',
                                      'u': u'1.65',
                                      'x': u'7.30'},
               u'Gabon v Morocco': {'1': u'2.35',
                                    '2': u'2.80',
                                    'Date': u'8 Oct',
                                    'League-division': u'World Cup Qual. CAF Group C',
                                    'Match-category': u'International',
                                    'Time': u'18:00',
                                    'match-code': u'6141',
                                    'o': u'1.50',
                                    'u': u'2.50',
                                    'x': u'2.95'},
               u'Ghana v Uganda': {'1': u'1.18',
                                   '2': u'9.80',
                                   'Date': u'7 Oct',
                                   'League-division': u'World Cup Qual. CAF Group E',
                                   'Match-category': u'International',
                                   'Time': u'18:30',
                                   'match-code': u'5084',
                                   'o': u'2.10',
                                   'u': u'1.70',
                                   'x': u'5.80'},
               u'Gresik United v Arema Indonesia': {'1': u'3.55',
                                                    '2': u'1.85',
                                                    'Date': u'7 Oct',
                                                    'League-division': u'Super League',
                                                    'Match-category': u'Indonesia',
                                                    'Time': u'17:00',
                                                    'match-code': u'5170',
                                                    'o': u'1.90',
                                                    'u': u'1.85',
                                                    'x': u'3.40'},
               u'HNK Gorica v NK Dinamo Zagreb II': {'1': u'2.90',
                                                     '2': u'2.10',
                                                     'Date': u'7 Oct',
                                                     'League-division': u'2. HNL',
                                                     'Match-category': u'Croatia',
                                                     'Time': u'16:00',
                                                     'match-code': u'5061',
                                                     'o': u'2.00',
                                                     'u': u'1.80',
                                                     'x': u'3.35'},
               u'Hannover 96 v Holstein Kiel': {'1': u'1.45',
                                                '2': u'5.80',
                                                'Date': u'7 Oct',
                                                'League-division': u'Club Friendly Games',
                                                'Match-category': u'International Clubs',
                                                'Time': u'17:30',
                                                'match-code': u'5248',
                                                'o': u'2.35',
                                                'u': u'1.60',
                                                'x': u'4.00'},
               u'Ivory Coast v Mali': {'1': u'1.45',
                                       '2': u'5.50',
                                       'Date': u'8 Oct',
                                       'League-division': u'World Cup Qual. CAF Group C',
                                       'Match-category': u'International',
                                       'Time': u'21:00',
                                       'match-code': u'6059',
                                       'o': u'2.20',
                                       'u': u'1.65',
                                       'x': u'3.90'},
               u'JSM Bejaia v ASM Oran': {'1': u'1.80',
                                          '2': u'4.50',
                                          'Date': u'7 Oct',
                                          'League-division': u'Ligue 2',
                                          'Match-category': u'Algeria',
                                          'Time': u'18:00',
                                          'match-code': u'5177',
                                          'o': u'1.60',
                                          'u': u'2.35',
                                          'x': u'2.95'},
               u'JSM Skikda v WA Boufarik': {'1': u'1.55',
                                             '2': u'5.50',
                                             'Date': u'7 Oct',
                                             'League-division': u'Ligue 2',
                                             'Match-category': u'Algeria',
                                             'Time': u'18:00',
                                             'match-code': u'5178',
                                             'o': u'1.60',
                                             'u': u'2.30',
                                             'x': u'3.50'},
               u'Karlsruher SC v Racing Strasbourg': {'1': u'1.85',
                                                      '2': u'3.60',
                                                      'Date': u'7 Oct',
                                                      'League-division': u'Club Friendly Games',
                                                      'Match-category': u'International Clubs',
                                                      'Time': u'18:30',
                                                      'match-code': u'5247',
                                                      'o': u'1.70',
                                                      'u': u'2.10',
                                                      'x': u'3.40'},
               u'Lithuania (U 21) v Slovenia (U 21)': {'1': u'5.80',
                                                       '2': u'1.45',
                                                       'Date': u'7 Oct',
                                                       'League-division': u'U21 EURO, Qualification, Group 2',
                                                       'Match-category': u'International Youth',
                                                       'Time': u'18:30',
                                                       'match-code': u'5073',
                                                       'o': u'1.85',
                                                       'u': u'1.90',
                                                       'x': u'3.85'},
               u'Luxembourg (U 21) v Armenia (U 21)': {'1': u'2.60',
                                                       '2': u'2.45',
                                                       'Date': u'7 Oct',
                                                       'League-division': u'U21 EURO, Qualification, Group 5',
                                                       'Match-category': u'International Youth',
                                                       'Time': u'17:30',
                                                       'match-code': u'5062',
                                                       'o': u'2.00',
                                                       'u': u'1.75',
                                                       'x': u'3.05'},
               u'Luxembourg v Sweden': {'1': u'9.00',
                                        '2': u'1.30',
                                        'Date': u'7 Oct',
                                        'League-division': u'World Cup Qual. UEFA Group A',
                                        'Match-category': u'International',
                                        'Time': u'21:45',
                                        'match-code': u'5547',
                                        'o': u'1.70',
                                        'u': u'2.10',
                                        'x': u'5.00'},
               u'MC EL Eulma v GC Mascara': {'1': u'1.70',
                                             '2': u'4.50',
                                             'Date': u'7 Oct',
                                             'League-division': u'Ligue 2',
                                             'Match-category': u'Algeria',
                                             'Time': u'17:00',
                                             'match-code': u'5176',
                                             'o': u'1.55',
                                             'u': u'2.35',
                                             'x': u'3.15'},
               u'MFK Okd Karvina v FC Zbrojovka Brno (U 21)': {'1': u'3.10',
                                                               '2': u'1.75',
                                                               'Date': u'7 Oct',
                                                               'League-division': u'U21',
                                                               'Match-category': u'Czech Republic',
                                                               'Time': u'13:00',
                                                               'match-code': u'5214',
                                                               'o': u'1.65',
                                                               'u': u'2.20',
                                                               'x': u'4.40'},
               u'Mumbai City FC v Northeast United FC': {'1': u'1.85',
                                                         '2': u'3.65',
                                                         'Date': u'7 Oct',
                                                         'League-division': u'Indian Super League',
                                                         'Match-category': u'India',
                                                         'Time': u'16:30',
                                                         'match-code': u'5139',
                                                         'o': u'1.85',
                                                         'u': u'1.95',
                                                         'x': u'3.35'},
               u'Netherlands (U 20) v USA (U 20)': {'1': u'2.10',
                                                    '2': u'2.80',
                                                    'Date': u'7 Oct',
                                                    'League-division': u'U20 Friendly Games',
                                                    'Match-category': u'International Youth',
                                                    'Time': u'17:00',
                                                    'match-code': u'5276',
                                                    'o': u'1.95',
                                                    'u': u'1.85',
                                                    'x': u'3.55'},
               u'Netherlands v Belarus': {'1': u'1.25',
                                          '2': u'10.50',
                                          'Date': u'7 Oct',
                                          'League-division': u'World Cup Qual. UEFA Group A',
                                          'Match-category': u'International',
                                          'Time': u'21:45',
                                          'match-code': u'5546',
                                          'o': u'1.60',
                                          'u': u'2.25',
                                          'x': u'5.50'},
               u'Netherlands v France': {'1': u'3.00',
                                         '2': u'2.35',
                                         'Date': u'10 Oct',
                                         'League-division': u'World Cup Qual. UEFA Group A',
                                         'Match-category': u'International',
                                         'Time': u'21:45',
                                         'match-code': u'1011',
                                         'o': u'2.20',
                                         'u': u'1.65',
                                         'x': u'3.10'},
               u'New Zealand v Jordan': {'1': u'1.25',
                                         '2': u'7.80',
                                         'Date': u'7 Oct',
                                         'League-division': u'U17 Womens World Cup, Group A',
                                         'Match-category': u'International Youth',
                                         'Time': u'16:00',
                                         'match-code': u'5160',
                                         'o': u'1.60',
                                         'u': u'2.25',
                                         'x': u'5.00'},
               u'Oman v Jordan': {'1': u'2.45',
                                  '2': u'2.70',
                                  'Date': u'7 Oct',
                                  'League-division': u'Int. Friendly Games',
                                  'Match-category': u'International',
                                  'Time': u'18:00',
                                  'match-code': u'5112',
                                  'o': u'2.10',
                                  'u': u'1.70',
                                  'x': u'3.15'},
               u'Paradou AC v RC Arbaa': {'1': u'1.30',
                                          '2': u'8.80',
                                          'Date': u'7 Oct',
                                          'League-division': u'Ligue 2',
                                          'Match-category': u'Algeria',
                                          'Time': u'18:00',
                                          'match-code': u'5180',
                                          'o': u'1.55',
                                          'u': u'2.35',
                                          'x': u'4.10'},
               u'Paraguay v Colombia': {'1': u'3.75',
                                        '2': u'3.15',
                                        'Date': u'7 Oct',
                                        'League-division': u'World Cup Qualification, CONMEBOL',
                                        'Match-category': u'International',
                                        'Time': u'02:30',
                                        'match-code': u'4475',
                                        'o': u'1.50',
                                        'u': u'2.30',
                                        'x': u'1.90'},
               u'Partick Thistle v Celtic Glasgow': {'1': u'4.10',
                                                     '2': u'1.60',
                                                     'Date': u'7 Oct',
                                                     'League-division': u'Development League',
                                                     'Match-category': u'Scotland',
                                                     'Time': u'15:00',
                                                     'match-code': u'5250',
                                                     'o': u'2.10',
                                                     'u': u'1.70',
                                                     'x': u'3.95'},
               u'Peru v Argentina': {'1': u'5.00',
                                     '2': u'1.75',
                                     'Date': u'7 Oct',
                                     'League-division': u'World Cup Qualification, CONMEBOL',
                                     'Match-category': u'International',
                                     'Time': u'05:15',
                                     'match-code': u'4482',
                                     'o': u'2.45',
                                     'u': u'1.55',
                                     'x': u'3.30'},
               u'Philippines v Bahrain': {'1': u'3.80',
                                          '2': u'1.85',
                                          'Date': u'7 Oct',
                                          'League-division': u'Int. Friendly Games',
                                          'Match-category': u'International',
                                          'Time': u'15:00',
                                          'match-code': u'5101',
                                          'o': u'1.90',
                                          'u': u'1.85',
                                          'x': u'3.40'},
               u'Senegal v Cape Verde': {'1': u'1.50',
                                         '2': u'5.80',
                                         'Date': u'8 Oct',
                                         'League-division': u'World Cup Qual. CAF Group D',
                                         'Match-category': u'International',
                                         'Time': u'23:00',
                                         'match-code': u'6140',
                                         'o': u'2.05',
                                         'u': u'1.75',
                                         'x': u'3.65'},
               u'Singapore v Malaysia': {'1': u'1.75',
                                         '2': u'4.10',
                                         'Date': u'7 Oct',
                                         'League-division': u'Int. Friendly Games',
                                         'Match-category': u'International',
                                         'Time': u'15:30',
                                         'match-code': u'5100',
                                         'o': u'1.80',
                                         'u': u'2.00',
                                         'x': u'3.45'},
               u'Spain (U 17 W) v Mexico (U 17 W)': {'1': u'1.55',
                                                     '2': u'4.50',
                                                     'Date': u'7 Oct',
                                                     'League-division': u'U17 Womens World Cup, Group A',
                                                     'Match-category': u'International Youth',
                                                     'Time': u'16:00',
                                                     'match-code': u'5146',
                                                     'o': u'1.80',
                                                     'u': u'2.00',
                                                     'x': u'4.10'},
               u'Tunisia v Guinea': {'1': u'1.75',
                                     '2': u'4.10',
                                     'Date': u'9 Oct',
                                     'League-division': u'World Cup Qual. CAF Group A',
                                     'Match-category': u'International',
                                     'Time': u'20:00',
                                     'match-code': u'7025',
                                     'o': u'2.40',
                                     'u': u'1.55',
                                     'x': u'3.30'},
               u'Volyn-D Lutsk (U 21) v Vorskla-D Poltava (U 21)': {'1': u'1.90',
                                                                    '2': u'2.85',
                                                                    'Date': u'7 Oct',
                                                                    'League-division': u'U21',
                                                                    'Match-category': u'Ukraine',
                                                                    'Time': u'13:00',
                                                                    'match-code': u'5275',
                                                                    'o': u'1.90',
                                                                    'u': u'1.85',
                                                                    'x': u'4.10'},
               u'Zambia v Nigeria': {'1': u'3.25',
                                     '2': u'2.00',
                                     'Date': u'9 Oct',
                                     'League-division': u'World Cup Qual. CAF Group B',
                                     'Match-category': u'International',
                                     'Time': u'15:30',
                                     'match-code': u'7558',
                                     'o': u'2.35',
                                     'u': u'1.55',
                                     'x': u'3.20'}},
 u'Futsal': {u'': {'1': u'',
                   '2': u'',
                   'Date': u'',
                   'League-division': u'',
                   'Match-category': u'',
                   'Time': u'',
                   'match-code': u'',
                   'o': u'',
                   'u': u'',
                   'x': u''},
             u'Progress Glazov v MFk Kprf': {'1': u'3.20',
                                             '2': u'1.75',
                                             'Date': u'7 Oct',
                                             'League-division': u'Superliga',
                                             'Match-category': u'Russia',
                                             'Time': u'17:00',
                                             'match-code': u'5223',
                                             'o': u'1.95',
                                             'u': u'1.65',
                                             'x': u'4.30'}},
 u'Golf': {u'': {'1': u'',
                 '2': u'',
                 'Date': u'',
                 'League-division': u'',
                 'Match-category': u'',
                 'Time': u'',
                 'match-code': u'',
                 'o': u'',
                 'u': u'',
                 'x': u''}},
 u'Handball': {u'': {'1': u'',
                     '2': u'',
                     'Date': u'',
                     'League-division': u'',
                     'Match-category': u'',
                     'Time': u'',
                     'match-code': u'',
                     'o': u'',
                     'u': u'',
                     'x': u''},
               u'BM Huesca v BM Sinfin': {'1': u'1.45',
                                          '2': u'3.30',
                                          'Date': u'7 Oct',
                                          'League-division': u'Asobal',
                                          'Match-category': u'Spain',
                                          'Time': u'21:30',
                                          'match-code': u'5029',
                                          'o': u'1.90',
                                          'u': u'1.70',
                                          'x': u'8.30'},
               u'EHV Aue v TV Emsdetten': {'1': u'1.55',
                                           '2': u'2.80',
                                           'Date': u'7 Oct',
                                           'League-division': u'2nd Bundesliga',
                                           'Match-category': u'Germany',
                                           'Time': u'20:00',
                                           'match-code': u'5210',
                                           'o': u'1.75',
                                           'u': u'1.80',
                                           'x': u'8.80'},
               u'Eger Sbs v Balmazujvarosi KK': {'1': u'1.65',
                                                 '2': u'2.55',
                                                 'Date': u'7 Oct',
                                                 'League-division': u'NB I',
                                                 'Match-category': u'Hungary',
                                                 'Time': u'19:00',
                                                 'match-code': u'5241',
                                                 'o': u'1.75',
                                                 'u': u'1.80',
                                                 'x': u'8.00'},
               u'Quabit BM Guadalajara v Frig Morrazo Cangas': {'1': u'1.65',
                                                                '2': u'2.60',
                                                                'Date': u'7 Oct',
                                                                'League-division': u'Asobal',
                                                                'Match-category': u'Spain',
                                                                'Time': u'21:30',
                                                                'match-code': u'5028',
                                                                'o': u'1.90',
                                                                'u': u'1.70',
                                                                'x': u'7.50'},
               u'SKP Bratislava v HC Thp Topvar Topolcany': {'1': u'5.50',
                                                             '2': u'1.16',
                                                             'Date': u'7 Oct',
                                                             'League-division': u'Extraliga',
                                                             'Match-category': u'Slovakia',
                                                             'Time': u'20:00',
                                                             'match-code': u'5255',
                                                             'o': u'1.80',
                                                             'u': u'1.80',
                                                             'x': u'12'},
               u'Skanderborg Handball v HC Midtjylland': {'1': u'2.75',
                                                          '2': u'1.60',
                                                          'Date': u'8 Oct',
                                                          'League-division': u'Handboldligaen',
                                                          'Match-category': u'Denmark',
                                                          'Time': u'16:00',
                                                          'match-code': u'8157',
                                                          'o': u'1.75',
                                                          'u': u'1.80',
                                                          'x': u'7.80'},
               u'TSV Gwd Minden v HC Erlangen': {'1': u'2.45',
                                                 '2': u'1.75',
                                                 'Date': u'7 Oct',
                                                 'League-division': u'Bundesliga',
                                                 'Match-category': u'Germany',
                                                 'Time': u'20:45',
                                                 'match-code': u'5136',
                                                 'o': u'1.80',
                                                 'u': u'1.80',
                                                 'x': u'7.50'},
               u'TVB 1898 Stuttgart v SC Magdeburg': {'1': u'2.70',
                                                      '2': u'1.60',
                                                      'Date': u'7 Oct',
                                                      'League-division': u'Bundesliga',
                                                      'Match-category': u'Germany',
                                                      'Time': u'20:45',
                                                      'match-code': u'5135',
                                                      'o': u'1.85',
                                                      'u': u'1.70',
                                                      'x': u'7.80'},
               u'Tusem Essen v Dessau-Rosslauer HV 2006': {'1': u'1.40',
                                                           '2': u'3.65',
                                                           'Date': u'7 Oct',
                                                           'League-division': u'2nd Bundesliga',
                                                           'Match-category': u'Germany',
                                                           'Time': u'20:30',
                                                           'match-code': u'5209',
                                                           'o': u'1.75',
                                                           'u': u'1.85',
                                                           'x': u'7.80'},
               u'Union Leoben v Moser Medical Uhk Krems': {'1': u'2.95',
                                                           '2': u'1.50',
                                                           'Date': u'7 Oct',
                                                           'League-division': u'HLA',
                                                           'Match-category': u'Austria',
                                                           'Time': u'20:30',
                                                           'match-code': u'5219',
                                                           'o': u'1.80',
                                                           'u': u'1.80',
                                                           'x': u'9.00'},
               u'Wisla Plock Ssa v MKB Veszprem KC': {'1': u'4.10',
                                                      '2': u'1.30',
                                                      'Date': u'8 Oct',
                                                      'League-division': u'Champions League, Group A',
                                                      'Match-category': u'International',
                                                      'Time': u'17:00',
                                                      'match-code': u'8031',
                                                      'o': u'1.85',
                                                      'u': u'1.75',
                                                      'x': u'10.75'}},
 u'Ice Hockey': {u'': {'1': u'',
                       '2': u'',
                       'Date': u'',
                       'League-division': u'',
                       'Match-category': u'',
                       'Time': u'',
                       'match-code': u'',
                       'o': u'',
                       'u': u'',
                       'x': u''},
                 u'Avto Yekaterinburg v Tolpar Ufa': {'1': u'2.10',
                                                      '2': u'2.50',
                                                      'Date': u'7 Oct',
                                                      'League-division': u'MHL',
                                                      'Match-category': u'Russia',
                                                      'Time': u'11:00',
                                                      'match-code': u'5161',
                                                      'o': u'2.05',
                                                      'u': u'1.60',
                                                      'x': u'4.10'},
                 u'Avtomobilist Yekaterinburg v Neftekhimik Nizhnekamsk': {'1': u'2.05',
                                                                           '2': u'3.05',
                                                                           'Date': u'7 Oct',
                                                                           'League-division': u'KHL',
                                                                           'Match-category': u'Russia',
                                                                           'Time': u'17:00',
                                                                           'match-code': u'5027',
                                                                           'o': u'2.05',
                                                                           'u': u'1.60',
                                                                           'x': u'3.85'},
                 u'Edmonton Oilers v Winnipeg Jets': {'1': u'2.20',
                                                      '2': u'2.50',
                                                      'Date': u'7 Oct',
                                                      'League-division': u'NHL, Preseason',
                                                      'Match-category': u'USA',
                                                      'Time': u'04:00',
                                                      'match-code': u'4327',
                                                      'o': u'1.90',
                                                      'u': u'1.65',
                                                      'x': u'3.85'},
                 u'Ermak Angarsk v Dynamo Balashikha': {'1': u'1.85',
                                                        '2': u'3.05',
                                                        'Date': u'7 Oct',
                                                        'League-division': u'VHL',
                                                        'Match-category': u'Russia',
                                                        'Time': u'14:00',
                                                        'match-code': u'5117',
                                                        'o': u'1.65',
                                                        'u': u'1.95',
                                                        'x': u'4.00'},
                 u'HC Barys Astana v HC Lada Togliatti': {'1': u'1.85',
                                                          '2': u'3.35',
                                                          'Date': u'7 Oct',
                                                          'League-division': u'KHL',
                                                          'Match-category': u'Russia',
                                                          'Time': u'16:30',
                                                          'match-code': u'5019',
                                                          'o': u'2.05',
                                                          'u': u'1.55',
                                                          'x': u'4.20'},
                 u'HC Chomutov v PSG Zlin': {'1': u'1.85',
                                             '2': u'3.25',
                                             'Date': u'7 Oct',
                                             'League-division': u'Extraliga',
                                             'Match-category': u'Czech Republic',
                                             'Time': u'18:30',
                                             'match-code': u'5020',
                                             'o': u'1.95',
                                             'u': u'1.65',
                                             'x': u'4.40'},
                 u'HC Kazzinc-Torpedo UK v Khimik Voskresensk': {'1': u'1.22',
                                                                 '2': u'7.00',
                                                                 'Date': u'7 Oct',
                                                                 'League-division': u'VHL',
                                                                 'Match-category': u'Russia',
                                                                 'Time': u'15:30',
                                                                 'match-code': u'5119',
                                                                 'o': u'1.70',
                                                                 'u': u'1.90',
                                                                 'x': u'6.30'},
                 u'HC Ocelari Trinec v HC Kometa Brno': {'1': u'2.10',
                                                         '2': u'2.75',
                                                         'Date': u'7 Oct',
                                                         'League-division': u'Extraliga',
                                                         'Match-category': u'Czech Republic',
                                                         'Time': u'18:00',
                                                         'match-code': u'5026',
                                                         'o': u'1.95',
                                                         'u': u'1.75',
                                                         'x': u'4.30'},
                 u'HC Yugra Khanty-Mansiysk v AK Bars Kazan': {'1': u'3.60',
                                                               '2': u'1.80',
                                                               'Date': u'7 Oct',
                                                               'League-division': u'KHL',
                                                               'Match-category': u'Russia',
                                                               'Time': u'17:00',
                                                               'match-code': u'5024',
                                                               'o': u'1.95',
                                                               'u': u'1.65',
                                                               'x': u'4.10'},
                 u'Liptovsky Mikulas v Mshk Zilina': {'1': u'2.05',
                                                      '2': u'2.60',
                                                      'Date': u'7 Oct',
                                                      'League-division': u'Extraliga',
                                                      'Match-category': u'Slovakia',
                                                      'Time': u'18:00',
                                                      'match-code': u'5037',
                                                      'o': u'1.95',
                                                      'u': u'1.65',
                                                      'x': u'4.20'},
                 u'Saryarka v THC Tver': {'1': u'2.00',
                                          '2': u'2.85',
                                          'Date': u'7 Oct',
                                          'League-division': u'VHL',
                                          'Match-category': u'Russia',
                                          'Time': u'16:00',
                                          'match-code': u'5116',
                                          'o': u'1.95',
                                          'u': u'1.65',
                                          'x': u'3.70'},
                 u'Ska-Neva v Toros Neftekamsk': {'1': u'2.30',
                                                  '2': u'2.45',
                                                  'Date': u'7 Oct',
                                                  'League-division': u'VHL',
                                                  'Match-category': u'Russia',
                                                  'Time': u'17:00',
                                                  'match-code': u'5114',
                                                  'o': u'1.80',
                                                  'u': u'1.75',
                                                  'x': u'3.70'},
                 u'Sokol Krasnoyarsk v HK Dinamo ST Petersburg': {'1': u'1.80',
                                                                  '2': u'3.40',
                                                                  'Date': u'7 Oct',
                                                                  'League-division': u'VHL',
                                                                  'Match-category': u'Russia',
                                                                  'Time': u'15:00',
                                                                  'match-code': u'5120',
                                                                  'o': u'2.00',
                                                                  'u': u'1.60',
                                                                  'x': u'3.80'},
                 u'Vancouver Canucks v Calgary Flames': {'1': u'2.35',
                                                         '2': u'2.40',
                                                         'Date': u'7 Oct',
                                                         'League-division': u'NHL, Preseason',
                                                         'Match-category': u'USA',
                                                         'Time': u'05:00',
                                                         'match-code': u'4323',
                                                         'o': u'1.95',
                                                         'u': u'1.65',
                                                         'x': u'3.70'}},
 u'Motorsport': {u'': {'1': u'',
                       '2': u'',
                       'Date': u'',
                       'League-division': u'',
                       'Match-category': u'',
                       'Time': u'',
                       'match-code': u'',
                       'o': u'',
                       'u': u'',
                       'x': u''}},
 u'Rugby': {u'': {'1': u'',
                  '2': u'',
                  'Date': u'',
                  'League-division': u'',
                  'Match-category': u'',
                  'Time': u'',
                  'match-code': u'',
                  'o': u'',
                  'u': u'',
                  'x': u''},
            u'Bath Rugby v Sale Sharks': {'1': u'1.18',
                                          '2': u'4.30',
                                          'Date': u'7 Oct',
                                          'League-division': u'English Premiership',
                                          'Match-category': u'Rugby Union',
                                          'Time': u'21:45',
                                          'match-code': u'5067',
                                          'o': u'1.75',
                                          'u': u'1.80',
                                          'x': u'22'},
            u'Canterbury v North Harbour': {'1': u'1.04',
                                            '2': u'7.30',
                                            'Date': u'7 Oct',
                                            'League-division': u'ITM Cup',
                                            'Match-category': u'Rugby Union',
                                            'Time': u'09:35',
                                            'match-code': u'5034',
                                            'o': u'1.80',
                                            'u': u'1.80',
                                            'x': u'46'},
            u'Connacht Rugby v Ulster Rugby': {'1': u'2.70',
                                               '2': u'1.45',
                                               'Date': u'7 Oct',
                                               'League-division': u'Pro 12',
                                               'Match-category': u'Rugby Union',
                                               'Time': u'21:35',
                                               'match-code': u'5066',
                                               'o': u'1.80',
                                               'u': u'1.80',
                                               'x': u'19.50'},
            u'Edinburgh Rugby v Benetton Treviso': {'1': u'1.10',
                                                    '2': u'6.00',
                                                    'Date': u'7 Oct',
                                                    'League-division': u'Pro 12',
                                                    'Match-category': u'Rugby Union',
                                                    'Time': u'21:35',
                                                    'match-code': u'5072',
                                                    'o': u'1.85',
                                                    'u': u'1.80',
                                                    'x': u'29'},
            u'Ospreys v Cardiff Blues': {'1': u'1.40',
                                         '2': u'2.95',
                                         'Date': u'7 Oct',
                                         'League-division': u'Pro 12',
                                         'Match-category': u'Rugby Union',
                                         'Time': u'21:35',
                                         'match-code': u'5095',
                                         'o': u'1.80',
                                         'u': u'1.85',
                                         'x': u'20'}},
 u'Snooker': {u'': {'1': u'',
                    '2': u'',
                    'Date': u'',
                    'League-division': u'',
                    'Match-category': u'',
                    'Time': u'',
                    'match-code': u'',
                    'o': u'',
                    'u': u'',
                    'x': u''}},
 u'Tennis': {u'': {'1': u'',
                   '2': u'',
                   'Date': u'',
                   'League-division': u'',
                   'Match-category': u'',
                   'Time': u'',
                   'match-code': u'',
                   'o': u'',
                   'u': u'',
                   'x': u''}},
 u'Volleyball': {u'': {'1': u'',
                       '2': u'',
                       'Date': u'',
                       'League-division': u'',
                       'Match-category': u'',
                       'Time': u'',
                       'match-code': u'',
                       'o': u'',
                       'u': u'',
                       'x': u''}}}